config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'bookings/new'
  # get 'airports/index'

  resources :flights
  resources :bookings
  resources :passengers
  root 'flights#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
  has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings
  scope :unique_departure_times, -> { pluck(:departure).map { |a| a.strftime('%B %d, %Y') }.uniq }

end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = Airport.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new(flight_id: params[:flight_id])
    @num_passengers = params[:num_passengers]
    @passengers = @booking.passengers.build
    @flight = Flight.find(params[:flight_id])
  end

  def create
    @booking = Booking.create(booking_params)
    # @booking.flight = @flight
    # @passengers = @booking.passengers
    if @booking.save
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show # fix
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    # @flights = Flight.where('DATE(departure) >= ?', Date.today)
    @dates = Flight.unique_departure_times
    @airport_options = Airport.all.map { |a| [a.city, a.id] }

    @departing_airport = params['depart']
    @arriving_airport = params['arrive']
    @date = params['date']

    # Takes selected departure date with midnight and gives range of whole day for search
    unless @date.blank?
      @time = Time.parse(@date)
      @start_time = Time.new(@time.year, @time.month, @time.day, 0, 0)
      @end_time = Time.new(@time.year, @time.month, @time.day, 11, 59)
    end

    @flights = Flight.where(
      departure_airport_id: @departing_airport,
      arrival_airport_id: @arriving_airport,
      departure: (@start_time..@end_time)
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def comment; end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def time_conversion(minutes)
    '%d:%02d' % minutes.divmod(60)
  end
end

app/views/airports/index.html.erb
<h1>Airports#index</h1>
<p>Find me in app/views/airports/index.html.erb</p>

app/views/bookings/_booking.html.erb
<h2>Origin: <%= "#{@booking.flight.departure_airport.city}" %></h2>
<h2>Destination: <%= "#{@booking.flight.arrival_airport.city}" %></h2>
<h3>Depature: <%= "#{@booking.flight.departure.strftime('%H:%M UTC on %B %d, %Y ')}" %></h3>
<h3>Flight Time: <%= "#{time_conversion(@booking.flight.duration)}" %></h3>

<h4>Booking was successful</h4>

app/views/bookings/_flight.html.erb
<h2>Origin: <%= "#{@flight.departure_airport.city}" %></h2>
<h2>Destination: <%= "#{@flight.arrival_airport.city}" %></h2>
<h3>Depature: <%= "#{@flight.departure.strftime('%H:%M UTC on %B %d, %Y ')}" %></h3>
<h3>Flight Time: <%= "#{time_conversion(@flight.duration)}" %></h3>

app/views/bookings/new.html.erb
<%= form_with model: @booking do |f| %>

<h2>Origin: <%= "#{@flight.departure_airport.city}" %></h2>
<h2>Destination: <%= "#{@flight.arrival_airport.city}" %></h2>
<h3>Depature: <%= "#{@flight.departure.strftime('%H:%M UTC on %B %d, %Y ')}" %></h3>
<h3>Flight Time: <%= "#{time_conversion(@flight.duration)}" %></h3>

    <%= f.hidden_field :flight_id, value: @flight.id %>

<% @num_passengers.to_i.times do %>
<%= f.fields_for :passengers do |sub_form|  %>
    <%= sub_form.label :name %>
    <%= sub_form.text_field :name%>
    <%= sub_form.label :email %>
    <%= sub_form.email_field :email %>
    
    <% end%>
<% end%>
<%= f.submit "Submit Booking"%>
<% end%>

app/views/bookings/show.html.erb
<%= render 'booking' %>

app/views/flights/_results.html.erb
<%= form_with(model: @flight, url: new_booking_path, method: "get") do |f| %>
    <%= f.hidden_field :num_passengers, value: params[:num_passengers] %>
<ul>
    <% @flights.each do |flight| %>
        <li>
        <%= flight.departure_airport.city %>
        <%= flight.arrival_airport.city  %>
        <%= flight.departure %>
        <%= f.radio_button :flight_id, flight.id %>
        </li>
    <% end %>
</ul>  
<%= f.submit "Book Flight" %>
<% end %>

app/views/flights/_search.html.erb
<%= form_with(url: "/flights", method: "get") do %>
<%= select_tag(:depart, options_for_select(@airport_options))%>
<%= select_tag(:arrive, options_for_select(@airport_options))%>
<%= select_tag(:date, options_for_select(@dates)) %>
<%= select_tag(:num_passengers, options_for_select(1..4)) %>
<%= submit_tag('Search') %>
<% end%>

app/views/flights/index.html.erb
<h1>Flights#index</h1>
<p>Find me in app/views/flights/index.html.erb</p>



<%= render "search" %>
<%= render "results" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# <main class="container mx-auto mt-28 px-5 flex"> %>
      <%= yield %>
    </main>
  </body>
</html>